project_id = "xlnuiukplynywobcgdeh"

[functions.evaluate]
verify_jwt = true

[functions.store-api-key]
verify_jwt = true

[functions.decrypt-api-key]
verify_jwt = true

[functions.test-connection]
verify_jwt = true
